"""phase2_intent_value_and_compliance_states

Revision ID: 30321bde3fc8
Revises: 
Create Date: 2026-05-23 16:38:58.184195

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '30321bde3fc8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_attr_state', sa.Column('intent_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_attr_state', 'intent_value')
    # ### end Alembic commands ###
