# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
"""Store immutable read observations.

Revision ID: 8a86079e0dfe
Revises: e4b8c2d6f0a1
Create Date: 2026-10-06 13:51:09.105193

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from nso_adapter.store.ddl import observation_immutability_ddl, observation_immutability_drop_ddl

# revision identifiers, used by Alembic.
revision: str = "8a86079e0dfe"
down_revision: str | Sequence[str] | None = "e4b8c2d6f0a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "read_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("source_epoch", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "family", "revision", name="uq_read_observation_revision"),
    )
    op.create_index(op.f("ix_read_observation_device_id"), "read_observation", ["device_id"], unique=False)
    # ### end Alembic commands ###
    for statement in observation_immutability_ddl():
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    for statement in observation_immutability_drop_ddl():
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_read_observation_device_id"), table_name="read_observation")
    op.drop_table("read_observation")
    # ### end Alembic commands ###
