# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
"""baseline schema — squash of all pre-M33 migrations.

Single autogenerated baseline (generated against PostgreSQL from the current
ORM models in nso_adapter.store.models). Replaces the prior 20-file chain,
which was non-functional from base (referenced tables only created by
create_all). No deployments existed, so version history was discarded.

create_all remains the test bootstrap (sqlite, in-process); this baseline is the
schema source for every real (PostgreSQL) DB, run via `alembic upgrade head` at
container start and in CI. Parity between the two is asserted by
tests/store/test_schema_parity.py (PostgreSQL).

Revision ID: d9f7d5098d8c
Revises:
Create Date: 2026-05-31 06:39:38.749460

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9f7d5098d8c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nso_instance", sa.String(length=128), nullable=False),
        sa.Column("nso_device_name", sa.String(length=256), nullable=False),
        sa.Column("netbox_device_id", sa.Integer(), nullable=True),
        sa.Column("ned_id", sa.String(length=256), nullable=True),
        sa.Column(
            "mapping_status",
            sa.Enum("mapped", "unmatched_device", "unmatched_interfaces", name="mappingstatus"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync_status", sa.Enum("succeeded", "failed", name="lastsyncstatus"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_netbox_device_id"), "devices", ["netbox_device_id"], unique=False)
    op.create_index(op.f("ix_devices_nso_device_name"), "devices", ["nso_device_name"], unique=False)
    op.create_table(
        "bgp_router_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("asn", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "asn", name="uq_bgprouterintent_identity"),
    )
    op.create_index(op.f("ix_bgp_router_intent_device_id"), "bgp_router_intent", ["device_id"], unique=False)
    op.create_table(
        "device_bgp_router",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("asn", sa.String(length=32), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "asn", name="uq_devicebgprouter_identity"),
    )
    op.create_index(op.f("ix_device_bgp_router_device_id"), "device_bgp_router", ["device_id"], unique=False)
    op.create_table(
        "device_isis_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("af", sa.String(length=8), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("circuit_type", sa.String(length=32), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "af", name="uq_deviceisisinterface_identity"),
    )
    op.create_index(op.f("ix_device_isis_interface_device_id"), "device_isis_interface", ["device_id"], unique=False)
    op.create_table(
        "device_isis_process",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("net", sa.String(length=64), nullable=True),
        sa.Column("is_type", sa.String(length=32), nullable=True),
        sa.Column("metric_style", sa.String(length=32), nullable=True),
        sa.Column("overload_bit", sa.Boolean(), nullable=True),
        sa.Column("area_auth_type", sa.String(length=32), nullable=True),
        sa.Column("area_auth_present", sa.Boolean(), nullable=True),
        sa.Column("domain_auth_type", sa.String(length=32), nullable=True),
        sa.Column("domain_auth_present", sa.Boolean(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_tag", name="uq_deviceisisprocess_identity"),
    )
    op.create_index(op.f("ix_device_isis_process_device_id"), "device_isis_process", ["device_id"], unique=False)
    op.create_table(
        "device_ospf_instance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=True),
        sa.Column("vrf", sa.String(length=64), nullable=False),
        sa.Column("areas", sa.JSON(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_id", name="uq_deviceospfinstance_identity"),
    )
    op.create_index(op.f("ix_device_ospf_instance_device_id"), "device_ospf_instance", ["device_id"], unique=False)
    op.create_table(
        "device_ospf_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("area_id", sa.String(length=64), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("auth_type", sa.String(length=32), nullable=True),
        sa.Column("auth_present", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_deviceospfinterface_identity"),
    )
    op.create_index(op.f("ix_device_ospf_interface_device_id"), "device_ospf_interface", ["device_id"], unique=False)
    op.create_table(
        "device_redistribution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("dest_protocol", sa.String(length=16), nullable=False),
        sa.Column("dest_ref", sa.String(length=128), nullable=False),
        sa.Column("source_protocol", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("route_map", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("metric_type", sa.String(length=16), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id",
            "dest_protocol",
            "dest_ref",
            "source_protocol",
            "source_ref",
            name="uq_deviceredistribution_identity",
        ),
    )
    op.create_index(op.f("ix_device_redistribution_device_id"), "device_redistribution", ["device_id"], unique=False)
    op.create_table(
        "device_route_policy_as_path",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drpap_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_as_path_device_id"), "device_route_policy_as_path", ["device_id"], unique=False
    )
    op.create_table(
        "device_route_policy_community_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drpcl_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_community_list_device_id"),
        "device_route_policy_community_list",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_prefix_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("family", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drppl_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_prefix_list_device_id"),
        "device_route_policy_prefix_list",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_route_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drprm_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_route_map_device_id"), "device_route_policy_route_map", ["device_id"], unique=False
    )
    op.create_table(
        "device_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("auto_apply", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_settings_device_id"), "device_settings", ["device_id"], unique=True)
    op.create_table(
        "device_static_route",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("next_hop", sa.String(length=64), nullable=False),
        sa.Column("interface_next_hop", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("permanent", sa.Boolean(), nullable=True),
        sa.Column("tag", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vrf", "prefix", "next_hop", name="uq_devicestaticroute_identity"),
    )
    op.create_index(op.f("ix_device_static_route_device_id"), "device_static_route", ["device_id"], unique=False)
    op.create_table(
        "interface_ip_address",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=256), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("vrf", sa.String(length=256), nullable=False),
        sa.Column("family", sa.String(length=8), nullable=False),
        sa.Column("secondary", sa.Boolean(), nullable=False),
        sa.Column("bound_port", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "address", "vrf", name="uq_ifipaddr_device_iface_addr_vrf"),
    )
    op.create_index(op.f("ix_interface_ip_address_device_id"), "interface_ip_address", ["device_id"], unique=False)
    op.create_table(
        "interfaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("netbox_interface_id", sa.Integer(), nullable=True),
        sa.Column("nso_if_key", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name"),
    )
    op.create_index(op.f("ix_interfaces_device_id"), "interfaces", ["device_id"], unique=False)
    op.create_table(
        "isis_interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("af", sa.String(length=8), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("circuit_type", sa.String(length=32), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "af", name="uq_isisinterfaceintent_identity"),
    )
    op.create_index(op.f("ix_isis_interface_intent_device_id"), "isis_interface_intent", ["device_id"], unique=False)
    op.create_table(
        "isis_process_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("net", sa.String(length=100), nullable=True),
        sa.Column("is_type", sa.String(length=50), nullable=True),
        sa.Column("metric_style", sa.String(length=20), nullable=True),
        sa.Column("overload_bit", sa.Boolean(), nullable=True),
        sa.Column("area_auth_type", sa.String(length=10), nullable=True),
        sa.Column("area_auth_key", sa.String(length=128), nullable=True),
        sa.Column("domain_auth_type", sa.String(length=10), nullable=True),
        sa.Column("domain_auth_key", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_tag", name="uq_isisprocessintent_identity"),
    )
    op.create_index(op.f("ix_isis_process_intent_device_id"), "isis_process_intent", ["device_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_type", sa.Enum("sync", "detect_drift", "connect", "apply", name="jobtype"), nullable=False),
        sa.Column("status", sa.Enum("queued", "running", "succeeded", "failed", name="jobstatus"), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lag_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("lag_id", sa.Integer(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_laginterface_device_name"),
    )
    op.create_index(op.f("ix_lag_interface_device_id"), "lag_interface", ["device_id"], unique=False)
    op.create_table(
        "managed_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "attribute"),
    )
    op.create_index(op.f("ix_managed_scope_device_id"), "managed_scope", ["device_id"], unique=False)
    op.create_table(
        "ospf_instance_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=True),
        sa.Column("vrf", sa.String(length=64), nullable=False),
        sa.Column("areas", sa.JSON(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_id", name="uq_ospfinstanceintent_identity"),
    )
    op.create_index(op.f("ix_ospf_instance_intent_device_id"), "ospf_instance_intent", ["device_id"], unique=False)
    op.create_table(
        "ospf_interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("area_id", sa.String(length=64), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("auth_type", sa.String(length=32), nullable=True),
        sa.Column("auth_key", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_ospfinterfaceintent_identity"),
    )
    op.create_index(op.f("ix_ospf_interface_intent_device_id"), "ospf_interface_intent", ["device_id"], unique=False)
    op.create_table(
        "redistribution_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("dest_protocol", sa.String(length=16), nullable=False),
        sa.Column("dest_ref", sa.String(length=128), nullable=False),
        sa.Column("source_protocol", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("route_map", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("metric_type", sa.String(length=16), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id",
            "dest_protocol",
            "dest_ref",
            "source_protocol",
            "source_ref",
            name="uq_redistributionintent_identity",
        ),
    )
    op.create_index(op.f("ix_redistribution_intent_device_id"), "redistribution_intent", ["device_id"], unique=False)
    op.create_table(
        "route_policy_object_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("entries", sa.JSON(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "family", "name", name="uq_rpoi_identity"),
    )
    op.create_index(
        op.f("ix_route_policy_object_intent_device_id"), "route_policy_object_intent", ["device_id"], unique=False
    )
    op.create_table(
        "snmp_community",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("community_hash", sa.String(length=64), nullable=False),
        sa.Column("access", sa.String(length=4), nullable=False),
        sa.Column("acl", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "community_hash", name="uq_snmpcommunity_device_hash"),
    )
    op.create_index(op.f("ix_snmp_community_device_id"), "snmp_community", ["device_id"], unique=False)
    op.create_table(
        "snmp_community_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("vault_ref", sa.String(length=512), nullable=False),
        sa.Column("access", sa.String(length=4), nullable=False),
        sa.Column("acl", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "label", name="uq_snmpcommintent_device_label"),
    )
    op.create_index(op.f("ix_snmp_community_intent_device_id"), "snmp_community_intent", ["device_id"], unique=False)
    op.create_table(
        "snmp_host",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=8), nullable=True),
        sa.Column("notify_type", sa.String(length=16), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_snmphost_device_address"),
    )
    op.create_index(op.f("ix_snmp_host_device_id"), "snmp_host", ["device_id"], unique=False)
    op.create_table(
        "snmp_host_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=4), nullable=False),
        sa.Column("notify_type", sa.String(length=8), nullable=False),
        sa.Column("community_or_user", sa.String(length=128), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_snmphostintent_device_addr"),
    )
    op.create_index(op.f("ix_snmp_host_intent_device_id"), "snmp_host_intent", ["device_id"], unique=False)
    op.create_table(
        "snmp_system_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("contact", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snmp_system_info_device_id"), "snmp_system_info", ["device_id"], unique=True)
    op.create_table(
        "snmp_system_info_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("contact", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snmp_system_info_intent_device_id"), "snmp_system_info_intent", ["device_id"], unique=True)
    op.create_table(
        "snmp_v3_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("has_auth_secret", sa.Boolean(), nullable=False),
        sa.Column("has_priv_secret", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "username", name="uq_snmpv3user_device_username"),
    )
    op.create_index(op.f("ix_snmp_v3_user_device_id"), "snmp_v3_user", ["device_id"], unique=False)
    op.create_table(
        "snmp_v3_user_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("auth_vault_ref", sa.String(length=512), nullable=True),
        sa.Column("priv_vault_ref", sa.String(length=512), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "username", name="uq_snmpv3userintent_device_user"),
    )
    op.create_index(op.f("ix_snmp_v3_user_intent_device_id"), "snmp_v3_user_intent", ["device_id"], unique=False)
    op.create_table(
        "static_route_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("next_hop", sa.String(length=64), nullable=False),
        sa.Column("interface_next_hop", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("permanent", sa.Boolean(), nullable=True),
        sa.Column("tag", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vrf", "prefix", "next_hop", name="uq_staticrouteintent_identity"),
    )
    op.create_index(op.f("ix_static_route_intent_device_id"), "static_route_intent", ["device_id"], unique=False)
    op.create_table(
        "bgp_scope_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("router_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["router_id"], ["bgp_router_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("router_id", "vrf", name="uq_bgpscopeintent_identity"),
    )
    op.create_index(op.f("ix_bgp_scope_intent_router_id"), "bgp_scope_intent", ["router_id"], unique=False)
    op.create_table(
        "device_bgp_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("router_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["router_id"], ["device_bgp_router.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("router_id", "vrf", name="uq_devicebgpscope_identity"),
    )
    op.create_index(op.f("ix_device_bgp_scope_router_id"), "device_bgp_scope", ["router_id"], unique=False)
    op.create_table(
        "device_route_policy_as_path_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("as_path_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["as_path_id"], ["device_route_policy_as_path.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("as_path_id", "sequence", name="uq_drpape_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_as_path_entry_as_path_id"),
        "device_route_policy_as_path_entry",
        ["as_path_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_community_list_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("community_list_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("community", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["community_list_id"], ["device_route_policy_community_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_list_id", "sequence", name="uq_drpcle_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_community_list_entry_community_list_id"),
        "device_route_policy_community_list_entry",
        ["community_list_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_prefix_list_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prefix_list_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("ge", sa.Integer(), nullable=True),
        sa.Column("le", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["prefix_list_id"], ["device_route_policy_prefix_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prefix_list_id", "sequence", name="uq_drpple_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_prefix_list_entry_prefix_list_id"),
        "device_route_policy_prefix_list_entry",
        ["prefix_list_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_route_map_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_map_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("match_prefix_lists", sa.JSON(), nullable=True),
        sa.Column("match_community_lists", sa.JSON(), nullable=True),
        sa.Column("match_as_paths", sa.JSON(), nullable=True),
        sa.Column("match_json", sa.Text(), nullable=True),
        sa.Column("set_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["route_map_id"], ["device_route_policy_route_map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_map_id", "sequence", name="uq_drprme_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_route_map_entry_route_map_id"),
        "device_route_policy_route_map_entry",
        ["route_map_id"],
        unique=False,
    )
    op.create_table(
        "interface_attr_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("nso_value", sa.Text(), nullable=True),
        sa.Column("netbox_value", sa.Text(), nullable=True),
        sa.Column("intent_value", sa.Text(), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "imported",
                "changed",
                "error",
                "unknown",
                "accepted",
                "deploying",
                "in_sync",
                "apply_failed",
                "drifted",
                name="syncstate",
            ),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interface_id"],
            ["interfaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "attribute"),
    )
    op.create_index(
        op.f("ix_interface_attr_state_interface_id"), "interface_attr_state", ["interface_id"], unique=False
    )
    op.create_table(
        "interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("intent_value", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interface_id"],
            ["interfaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "attribute"),
    )
    op.create_index(op.f("ix_interface_intent_interface_id"), "interface_intent", ["interface_id"], unique=False)
    op.create_table(
        "interface_ip_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("vrf", sa.String(length=256), nullable=False),
        sa.Column("family", sa.String(length=8), nullable=False),
        sa.Column("secondary", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["interface_id"], ["interfaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "address", "vrf", name="uq_ifipintent_iface_addr_vrf"),
    )
    op.create_index(op.f("ix_interface_ip_intent_interface_id"), "interface_ip_intent", ["interface_id"], unique=False)
    op.create_table(
        "lag_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lag_interface_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=256), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["lag_interface_id"], ["lag_interface.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lag_interface_id", "interface_name", name="uq_lagmember_lag_iface"),
    )
    op.create_index(op.f("ix_lag_member_lag_interface_id"), "lag_member", ["lag_interface_id"], unique=False)
    op.create_table(
        "bgp_af_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["bgp_scope_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "af", name="uq_bgpafintent_identity"),
    )
    op.create_index(op.f("ix_bgp_af_intent_scope_id"), "bgp_af_intent", ["scope_id"], unique=False)
    op.create_table(
        "bgp_peer_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("peer_address", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("peer_group", sa.String(length=128), nullable=True),
        sa.Column("remote_as", sa.String(length=32), nullable=True),
        sa.Column("local_as", sa.String(length=32), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["scope_id"], ["bgp_scope_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "peer_address", name="uq_bgppeerintent_identity"),
    )
    op.create_index(op.f("ix_bgp_peer_intent_scope_id"), "bgp_peer_intent", ["scope_id"], unique=False)
    op.create_table(
        "device_bgp_address_family",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["device_bgp_scope.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "af", name="uq_devicebgpaf_identity"),
    )
    op.create_index(
        op.f("ix_device_bgp_address_family_scope_id"), "device_bgp_address_family", ["scope_id"], unique=False
    )
    op.create_table(
        "device_bgp_peer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("peer_address", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("peer_group", sa.String(length=128), nullable=True),
        sa.Column("remote_as", sa.String(length=32), nullable=True),
        sa.Column("local_as", sa.String(length=32), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["scope_id"], ["device_bgp_scope.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "peer_address", name="uq_devicebgppeer_identity"),
    )
    op.create_index(op.f("ix_device_bgp_peer_scope_id"), "device_bgp_peer", ["scope_id"], unique=False)
    op.create_table(
        "bgp_peer_af_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("routemap_in", sa.String(length=255), nullable=True),
        sa.Column("routemap_out", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_in", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_out", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["peer_id"], ["bgp_peer_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("peer_id", "af", name="uq_bgppeerafintent_identity"),
    )
    op.create_index(op.f("ix_bgp_peer_af_intent_peer_id"), "bgp_peer_af_intent", ["peer_id"], unique=False)
    op.create_table(
        "device_bgp_peer_af",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("routemap_in", sa.String(length=255), nullable=True),
        sa.Column("routemap_out", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_in", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_out", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["peer_id"], ["device_bgp_peer.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("peer_id", "af", name="uq_devicebgppeeraf_identity"),
    )
    op.create_index(op.f("ix_device_bgp_peer_af_peer_id"), "device_bgp_peer_af", ["peer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_bgp_peer_af_peer_id"), table_name="device_bgp_peer_af")
    op.drop_table("device_bgp_peer_af")
    op.drop_index(op.f("ix_bgp_peer_af_intent_peer_id"), table_name="bgp_peer_af_intent")
    op.drop_table("bgp_peer_af_intent")
    op.drop_index(op.f("ix_device_bgp_peer_scope_id"), table_name="device_bgp_peer")
    op.drop_table("device_bgp_peer")
    op.drop_index(op.f("ix_device_bgp_address_family_scope_id"), table_name="device_bgp_address_family")
    op.drop_table("device_bgp_address_family")
    op.drop_index(op.f("ix_bgp_peer_intent_scope_id"), table_name="bgp_peer_intent")
    op.drop_table("bgp_peer_intent")
    op.drop_index(op.f("ix_bgp_af_intent_scope_id"), table_name="bgp_af_intent")
    op.drop_table("bgp_af_intent")
    op.drop_index(op.f("ix_lag_member_lag_interface_id"), table_name="lag_member")
    op.drop_table("lag_member")
    op.drop_index(op.f("ix_interface_ip_intent_interface_id"), table_name="interface_ip_intent")
    op.drop_table("interface_ip_intent")
    op.drop_index(op.f("ix_interface_intent_interface_id"), table_name="interface_intent")
    op.drop_table("interface_intent")
    op.drop_index(op.f("ix_interface_attr_state_interface_id"), table_name="interface_attr_state")
    op.drop_table("interface_attr_state")
    op.drop_index(
        op.f("ix_device_route_policy_route_map_entry_route_map_id"), table_name="device_route_policy_route_map_entry"
    )
    op.drop_table("device_route_policy_route_map_entry")
    op.drop_index(
        op.f("ix_device_route_policy_prefix_list_entry_prefix_list_id"),
        table_name="device_route_policy_prefix_list_entry",
    )
    op.drop_table("device_route_policy_prefix_list_entry")
    op.drop_index(
        op.f("ix_device_route_policy_community_list_entry_community_list_id"),
        table_name="device_route_policy_community_list_entry",
    )
    op.drop_table("device_route_policy_community_list_entry")
    op.drop_index(
        op.f("ix_device_route_policy_as_path_entry_as_path_id"), table_name="device_route_policy_as_path_entry"
    )
    op.drop_table("device_route_policy_as_path_entry")
    op.drop_index(op.f("ix_device_bgp_scope_router_id"), table_name="device_bgp_scope")
    op.drop_table("device_bgp_scope")
    op.drop_index(op.f("ix_bgp_scope_intent_router_id"), table_name="bgp_scope_intent")
    op.drop_table("bgp_scope_intent")
    op.drop_index(op.f("ix_static_route_intent_device_id"), table_name="static_route_intent")
    op.drop_table("static_route_intent")
    op.drop_index(op.f("ix_snmp_v3_user_intent_device_id"), table_name="snmp_v3_user_intent")
    op.drop_table("snmp_v3_user_intent")
    op.drop_index(op.f("ix_snmp_v3_user_device_id"), table_name="snmp_v3_user")
    op.drop_table("snmp_v3_user")
    op.drop_index(op.f("ix_snmp_system_info_intent_device_id"), table_name="snmp_system_info_intent")
    op.drop_table("snmp_system_info_intent")
    op.drop_index(op.f("ix_snmp_system_info_device_id"), table_name="snmp_system_info")
    op.drop_table("snmp_system_info")
    op.drop_index(op.f("ix_snmp_host_intent_device_id"), table_name="snmp_host_intent")
    op.drop_table("snmp_host_intent")
    op.drop_index(op.f("ix_snmp_host_device_id"), table_name="snmp_host")
    op.drop_table("snmp_host")
    op.drop_index(op.f("ix_snmp_community_intent_device_id"), table_name="snmp_community_intent")
    op.drop_table("snmp_community_intent")
    op.drop_index(op.f("ix_snmp_community_device_id"), table_name="snmp_community")
    op.drop_table("snmp_community")
    op.drop_index(op.f("ix_route_policy_object_intent_device_id"), table_name="route_policy_object_intent")
    op.drop_table("route_policy_object_intent")
    op.drop_index(op.f("ix_redistribution_intent_device_id"), table_name="redistribution_intent")
    op.drop_table("redistribution_intent")
    op.drop_index(op.f("ix_ospf_interface_intent_device_id"), table_name="ospf_interface_intent")
    op.drop_table("ospf_interface_intent")
    op.drop_index(op.f("ix_ospf_instance_intent_device_id"), table_name="ospf_instance_intent")
    op.drop_table("ospf_instance_intent")
    op.drop_index(op.f("ix_managed_scope_device_id"), table_name="managed_scope")
    op.drop_table("managed_scope")
    op.drop_index(op.f("ix_lag_interface_device_id"), table_name="lag_interface")
    op.drop_table("lag_interface")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_isis_process_intent_device_id"), table_name="isis_process_intent")
    op.drop_table("isis_process_intent")
    op.drop_index(op.f("ix_isis_interface_intent_device_id"), table_name="isis_interface_intent")
    op.drop_table("isis_interface_intent")
    op.drop_index(op.f("ix_interfaces_device_id"), table_name="interfaces")
    op.drop_table("interfaces")
    op.drop_index(op.f("ix_interface_ip_address_device_id"), table_name="interface_ip_address")
    op.drop_table("interface_ip_address")
    op.drop_index(op.f("ix_device_static_route_device_id"), table_name="device_static_route")
    op.drop_table("device_static_route")
    op.drop_index(op.f("ix_device_settings_device_id"), table_name="device_settings")
    op.drop_table("device_settings")
    op.drop_index(op.f("ix_device_route_policy_route_map_device_id"), table_name="device_route_policy_route_map")
    op.drop_table("device_route_policy_route_map")
    op.drop_index(op.f("ix_device_route_policy_prefix_list_device_id"), table_name="device_route_policy_prefix_list")
    op.drop_table("device_route_policy_prefix_list")
    op.drop_index(
        op.f("ix_device_route_policy_community_list_device_id"), table_name="device_route_policy_community_list"
    )
    op.drop_table("device_route_policy_community_list")
    op.drop_index(op.f("ix_device_route_policy_as_path_device_id"), table_name="device_route_policy_as_path")
    op.drop_table("device_route_policy_as_path")
    op.drop_index(op.f("ix_device_redistribution_device_id"), table_name="device_redistribution")
    op.drop_table("device_redistribution")
    op.drop_index(op.f("ix_device_ospf_interface_device_id"), table_name="device_ospf_interface")
    op.drop_table("device_ospf_interface")
    op.drop_index(op.f("ix_device_ospf_instance_device_id"), table_name="device_ospf_instance")
    op.drop_table("device_ospf_instance")
    op.drop_index(op.f("ix_device_isis_process_device_id"), table_name="device_isis_process")
    op.drop_table("device_isis_process")
    op.drop_index(op.f("ix_device_isis_interface_device_id"), table_name="device_isis_interface")
    op.drop_table("device_isis_interface")
    op.drop_index(op.f("ix_device_bgp_router_device_id"), table_name="device_bgp_router")
    op.drop_table("device_bgp_router")
    op.drop_index(op.f("ix_bgp_router_intent_device_id"), table_name="bgp_router_intent")
    op.drop_table("bgp_router_intent")
    op.drop_index(op.f("ix_devices_nso_device_name"), table_name="devices")
    op.drop_index(op.f("ix_devices_netbox_device_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
