# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
"""baseline schema squash

Revision ID: f556ce117498
Revises:
Create Date: 2026-07-01 15:26:57.885271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f556ce117498"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_capability",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ned_id", sa.String(length=256), nullable=False),
        sa.Column("sw_version", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ned_id", "sw_version", "scope", "name", name="uq_device_capability"),
    )
    op.create_index(op.f("ix_device_capability_ned_id"), "device_capability", ["ned_id"], unique=False)
    op.create_index(op.f("ix_device_capability_sw_version"), "device_capability", ["sw_version"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nso_instance", sa.String(length=128), nullable=False),
        sa.Column("nso_device_name", sa.String(length=256), nullable=False),
        sa.Column("netbox_device_id", sa.Integer(), nullable=True),
        sa.Column("ned_id", sa.String(length=256), nullable=True),
        sa.Column("sw_version", sa.String(length=128), nullable=True),
        sa.Column(
            "mapping_status",
            sa.Enum("mapped", "unmatched_device", "unmatched_interfaces", name="mappingstatus"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync_status", sa.Enum("succeeded", "failed", name="lastsyncstatus"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_netbox_device_id"), "devices", ["netbox_device_id"], unique=False)
    op.create_index(op.f("ix_devices_nso_device_name"), "devices", ["nso_device_name"], unique=False)
    op.create_table(
        "failover_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("primary_probe_interval", sa.Integer(), server_default=sa.text("15"), nullable=False),
        sa.Column("oob_probe_interval", sa.Integer(), server_default=sa.text("360"), nullable=False),
        sa.Column("failure_threshold", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("success_threshold", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("probe_timeout", sa.Float(), server_default=sa.text("10.0"), nullable=False),
        sa.Column("probe_concurrency", sa.Integer(), server_default=sa.text("8"), nullable=False),
        sa.Column("max_flips_per_tick", sa.Integer(), server_default=sa.text("8"), nullable=False),
        sa.Column("sync_from_after_switch", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bfd_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("min_tx", sa.Integer(), nullable=True),
        sa.Column("min_rx", sa.Integer(), nullable=True),
        sa.Column("multiplier", sa.Integer(), nullable=True),
        sa.Column("micro_bfd", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_bfdintent_identity"),
    )
    op.create_index(op.f("ix_bfd_intent_device_id"), "bfd_intent", ["device_id"], unique=False)
    op.create_table(
        "bgp_router_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("asn", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "asn", name="uq_bgprouterintent_identity"),
    )
    op.create_index(op.f("ix_bgp_router_intent_device_id"), "bgp_router_intent", ["device_id"], unique=False)
    op.create_table(
        "device_bfd_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("bound_port", sa.String(length=256), nullable=True),
        sa.Column("min_tx", sa.Integer(), nullable=True),
        sa.Column("min_rx", sa.Integer(), nullable=True),
        sa.Column("multiplier", sa.Integer(), nullable=True),
        sa.Column("micro_bfd", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_devicebfdinterface_identity"),
    )
    op.create_index(op.f("ix_device_bfd_interface_device_id"), "device_bfd_interface", ["device_id"], unique=False)
    op.create_table(
        "device_bgp_router",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("asn", sa.String(length=32), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "asn", name="uq_devicebgprouter_identity"),
    )
    op.create_index(op.f("ix_device_bgp_router_device_id"), "device_bgp_router", ["device_id"], unique=False)
    op.create_table(
        "device_failover",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("primary_ip", sa.String(length=64), nullable=True),
        sa.Column("oob_ip", sa.String(length=64), nullable=True),
        sa.Column("active_address", sa.String(length=16), server_default=sa.text("'primary'"), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("consecutive_successes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("manual_override", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("oob_healthy", sa.Boolean(), nullable=True),
        sa.Column("oob_health_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_probe_at", sa.DateTime(), nullable=True),
        sa.Column("last_probe_result", sa.String(length=16), nullable=True),
        sa.Column("last_switch_at", sa.DateTime(), nullable=True),
        sa.Column("next_primary_probe_at", sa.DateTime(), nullable=True),
        sa.Column("next_oob_probe_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_failover_device_id"), "device_failover", ["device_id"], unique=True)
    op.create_table(
        "device_interface_mtu",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("mtu", sa.Integer(), nullable=True),
        sa.Column("ip_mtu", sa.Integer(), nullable=True),
        sa.Column("mpls_mtu", sa.Integer(), nullable=True),
        sa.Column("bound_port", sa.String(length=128), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_deviceifmtu_identity"),
    )
    op.create_index(op.f("ix_device_interface_mtu_device_id"), "device_interface_mtu", ["device_id"], unique=False)
    op.create_table(
        "device_isis_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("af", sa.String(length=8), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("circuit_type", sa.String(length=32), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("bound_port", sa.String(length=256), nullable=True),
        sa.Column("hello_auth_type", sa.String(length=32), nullable=True),
        sa.Column("hello_auth_present", sa.Boolean(), nullable=True),
        sa.Column("bfd_enabled", sa.Boolean(), nullable=True),
        sa.Column("csnp_interval", sa.Integer(), nullable=True),
        sa.Column("retransmit_interval", sa.Integer(), nullable=True),
        sa.Column("lsp_interval", sa.Integer(), nullable=True),
        sa.Column("mesh_group", sa.String(length=32), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("levels", sa.JSON(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "af", name="uq_deviceisisinterface_identity"),
    )
    op.create_index(op.f("ix_device_isis_interface_device_id"), "device_isis_interface", ["device_id"], unique=False)
    op.create_table(
        "device_isis_process",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("net", sa.String(length=64), nullable=True),
        sa.Column("is_type", sa.String(length=32), nullable=True),
        sa.Column("metric_style", sa.String(length=32), nullable=True),
        sa.Column("overload_bit", sa.Boolean(), nullable=True),
        sa.Column("area_auth_type", sa.String(length=32), nullable=True),
        sa.Column("area_auth_present", sa.Boolean(), nullable=True),
        sa.Column("area_auth_key", sa.String(length=128), nullable=True),
        sa.Column("domain_auth_type", sa.String(length=32), nullable=True),
        sa.Column("domain_auth_present", sa.Boolean(), nullable=True),
        sa.Column("domain_auth_key", sa.String(length=128), nullable=True),
        sa.Column("spf_initial_wait", sa.Integer(), nullable=True),
        sa.Column("spf_max_wait", sa.Integer(), nullable=True),
        sa.Column("lsp_initial_wait", sa.Integer(), nullable=True),
        sa.Column("lsp_max_wait", sa.Integer(), nullable=True),
        sa.Column("lsp_lifetime", sa.Integer(), nullable=True),
        sa.Column("lsp_refresh_interval", sa.Integer(), nullable=True),
        sa.Column("lsp_mtu", sa.Integer(), nullable=True),
        sa.Column("overload_on_startup", sa.Boolean(), nullable=True),
        sa.Column("overload_timeout", sa.Integer(), nullable=True),
        sa.Column("te_enabled", sa.Boolean(), nullable=True),
        sa.Column("sr_enabled", sa.Boolean(), nullable=True),
        sa.Column("sr_node_msd", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("maximum_paths", sa.Integer(), nullable=True),
        sa.Column("reference_bandwidth", sa.BigInteger(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("levels", sa.JSON(), nullable=True),
        sa.Column("segment_routing", sa.JSON(), nullable=True),
        sa.Column("flex_algos", sa.JSON(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_tag", name="uq_deviceisisprocess_identity"),
    )
    op.create_index(op.f("ix_device_isis_process_device_id"), "device_isis_process", ["device_id"], unique=False)
    op.create_table(
        "device_l2_sap",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=64), nullable=False),
        sa.Column("service_type", sa.String(length=16), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("sap_id", sa.String(length=64), nullable=False),
        sa.Column("port", sa.String(length=64), nullable=False),
        sa.Column("outer_tag", sa.Integer(), nullable=True),
        sa.Column("inner_tag", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "service_name", "sap_id", name="uq_devicel2sap_identity"),
    )
    op.create_index(op.f("ix_device_l2_sap_device_id"), "device_l2_sap", ["device_id"], unique=False)
    op.create_table(
        "device_logging_host",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("facility", sa.String(length=32), nullable=True),
        sa.Column("transport", sa.String(length=16), nullable=True),
        sa.Column("vrf", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_logginghost_device_address"),
    )
    op.create_index(op.f("ix_device_logging_host_device_id"), "device_logging_host", ["device_id"], unique=False)
    op.create_table(
        "device_ospf_instance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.String(length=64), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=True),
        sa.Column("vrf", sa.String(length=64), nullable=False),
        sa.Column("areas", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_id", name="uq_deviceospfinstance_identity"),
    )
    op.create_index(op.f("ix_device_ospf_instance_device_id"), "device_ospf_instance", ["device_id"], unique=False)
    op.create_table(
        "device_ospf_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("process_id", sa.String(length=64), nullable=True),
        sa.Column("area_id", sa.String(length=64), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("auth_type", sa.String(length=32), nullable=True),
        sa.Column("auth_present", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_deviceospfinterface_identity"),
    )
    op.create_index(op.f("ix_device_ospf_interface_device_id"), "device_ospf_interface", ["device_id"], unique=False)
    op.create_table(
        "device_redistribution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("dest_protocol", sa.String(length=16), nullable=False),
        sa.Column("dest_ref", sa.String(length=128), nullable=False),
        sa.Column("source_protocol", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("route_map", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("metric_type", sa.String(length=16), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id",
            "dest_protocol",
            "dest_ref",
            "source_protocol",
            "source_ref",
            name="uq_deviceredistribution_identity",
        ),
    )
    op.create_index(op.f("ix_device_redistribution_device_id"), "device_redistribution", ["device_id"], unique=False)
    op.create_table(
        "device_route_policy_as_path",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drpap_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_as_path_device_id"), "device_route_policy_as_path", ["device_id"], unique=False
    )
    op.create_table(
        "device_route_policy_community_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("invert_match", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drpcl_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_community_list_device_id"),
        "device_route_policy_community_list",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_prefix_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("family", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drppl_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_prefix_list_device_id"),
        "device_route_policy_prefix_list",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_route_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_drprm_identity"),
    )
    op.create_index(
        op.f("ix_device_route_policy_route_map_device_id"), "device_route_policy_route_map", ["device_id"], unique=False
    )
    op.create_table(
        "device_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("auto_apply", sa.Boolean(), nullable=False),
        sa.Column("sync_before_apply", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_settings_device_id"), "device_settings", ["device_id"], unique=True)
    op.create_table(
        "device_static_route",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("next_hop", sa.String(length=64), nullable=False),
        sa.Column("interface_next_hop", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("permanent", sa.Boolean(), nullable=True),
        sa.Column("tag", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vrf", "prefix", "next_hop", name="uq_devicestaticroute_identity"),
    )
    op.create_index(op.f("ix_device_static_route_device_id"), "device_static_route", ["device_id"], unique=False)
    op.create_table(
        "device_subinterface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("parent_interface", sa.String(length=128), nullable=True),
        sa.Column("dot1q_vlan", sa.Integer(), nullable=True),
        sa.Column("sub_type", sa.String(length=16), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_devicesubif_identity"),
    )
    op.create_index(op.f("ix_device_subinterface_device_id"), "device_subinterface", ["device_id"], unique=False)
    op.create_table(
        "device_svi",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.Column("svi_type", sa.String(length=8), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_devicesvi_identity"),
    )
    op.create_index(op.f("ix_device_svi_device_id"), "device_svi", ["device_id"], unique=False)
    op.create_table(
        "device_vlan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vlan_id", name="uq_devicevlan_identity"),
    )
    op.create_index(op.f("ix_device_vlan_device_id"), "device_vlan", ["device_id"], unique=False)
    op.create_table(
        "interface_ip_address",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=256), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("vrf", sa.String(length=256), nullable=False),
        sa.Column("family", sa.String(length=8), nullable=False),
        sa.Column("secondary", sa.Boolean(), nullable=False),
        sa.Column("bound_port", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "address", "vrf", name="uq_ifipaddr_device_iface_addr_vrf"),
    )
    op.create_index(op.f("ix_interface_ip_address_device_id"), "interface_ip_address", ["device_id"], unique=False)
    op.create_table(
        "interface_mtu_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("mtu", sa.Integer(), nullable=True),
        sa.Column("ip_mtu", sa.Integer(), nullable=True),
        sa.Column("mpls_mtu", sa.Integer(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_ifmtuintent_identity"),
    )
    op.create_index(op.f("ix_interface_mtu_intent_device_id"), "interface_mtu_intent", ["device_id"], unique=False)
    op.create_table(
        "interfaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("netbox_interface_id", sa.Integer(), nullable=True),
        sa.Column("nso_if_key", sa.String(length=256), nullable=True),
        sa.Column("parent_binding", sa.String(length=256), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=True),
        sa.Column("encap_tag", sa.String(length=64), nullable=True),
        sa.Column("vrf", sa.String(length=256), nullable=True),
        sa.Column("service", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name"),
    )
    op.create_index(op.f("ix_interfaces_device_id"), "interfaces", ["device_id"], unique=False)
    op.create_table(
        "isis_flex_algo_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("algo_id", sa.Integer(), nullable=False),
        sa.Column("metric_type", sa.String(length=40), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("admin_group_exclude", sa.String(length=200), nullable=True),
        sa.Column("admin_group_include_any", sa.String(length=200), nullable=True),
        sa.Column("admin_group_include_all", sa.String(length=200), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_tag", "algo_id", name="uq_isisflexalgointent_identity"),
    )
    op.create_index(op.f("ix_isis_flex_algo_intent_device_id"), "isis_flex_algo_intent", ["device_id"], unique=False)
    op.create_table(
        "isis_interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("af", sa.String(length=8), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("circuit_type", sa.String(length=32), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", "af", name="uq_isisinterfaceintent_identity"),
    )
    op.create_index(op.f("ix_isis_interface_intent_device_id"), "isis_interface_intent", ["device_id"], unique=False)
    op.create_table(
        "isis_process_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_tag", sa.String(length=128), nullable=False),
        sa.Column("net", sa.String(length=100), nullable=True),
        sa.Column("is_type", sa.String(length=50), nullable=True),
        sa.Column("metric_style", sa.String(length=20), nullable=True),
        sa.Column("overload_bit", sa.Boolean(), nullable=True),
        sa.Column("area_auth_type", sa.String(length=10), nullable=True),
        sa.Column("area_auth_key", sa.String(length=128), nullable=True),
        sa.Column("domain_auth_type", sa.String(length=10), nullable=True),
        sa.Column("domain_auth_key", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_tag", name="uq_isisprocessintent_identity"),
    )
    op.create_index(op.f("ix_isis_process_intent_device_id"), "isis_process_intent", ["device_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "job_type",
            sa.Enum("sync", "detect_drift", "connect", "apply", "removal", "provision", name="jobtype"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("queued", "running", "succeeded", "failed", name="jobstatus"), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "l2_sap_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=64), nullable=False),
        sa.Column("service_type", sa.String(length=16), nullable=False),
        sa.Column("sap_id", sa.String(length=64), nullable=False),
        sa.Column("port", sa.String(length=64), nullable=False),
        sa.Column("outer_tag", sa.Integer(), nullable=True),
        sa.Column("inner_tag", sa.Integer(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "service_name", "sap_id", name="uq_l2sapintent_identity"),
    )
    op.create_index(op.f("ix_l2_sap_intent_device_id"), "l2_sap_intent", ["device_id"], unique=False)
    op.create_table(
        "lag_bundle_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("lag_id", sa.Integer(), nullable=False),
        sa.Column("min_links", sa.Integer(), nullable=True),
        sa.Column("system_priority", sa.Integer(), nullable=True),
        sa.Column("system_id", sa.String(length=17), nullable=True),
        sa.Column("timer", sa.String(length=8), nullable=True),
        sa.Column("admin_key", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "lag_id", name="uq_lag_bundle_config_device_lag"),
    )
    op.create_index(op.f("ix_lag_bundle_config_device_id"), "lag_bundle_config", ["device_id"], unique=False)
    op.create_table(
        "lag_interface",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("lag_id", sa.Integer(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name", name="uq_laginterface_device_name"),
    )
    op.create_index(op.f("ix_lag_interface_device_id"), "lag_interface", ["device_id"], unique=False)
    op.create_table(
        "logging_host_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("facility", sa.String(length=32), nullable=False),
        sa.Column("transport", sa.String(length=16), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_logginghostintent_identity"),
    )
    op.create_index(op.f("ix_logging_host_intent_device_id"), "logging_host_intent", ["device_id"], unique=False)
    op.create_table(
        "managed_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "attribute"),
    )
    op.create_index(op.f("ix_managed_scope_device_id"), "managed_scope", ["device_id"], unique=False)
    op.create_table(
        "ospf_instance_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.String(length=64), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=True),
        sa.Column("vrf", sa.String(length=64), nullable=False),
        sa.Column("areas", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "process_id", name="uq_ospfinstanceintent_identity"),
    )
    op.create_index(op.f("ix_ospf_instance_intent_device_id"), "ospf_instance_intent", ["device_id"], unique=False)
    op.create_table(
        "ospf_interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("process_id", sa.String(length=64), nullable=True),
        sa.Column("area_id", sa.String(length=64), nullable=True),
        sa.Column("passive", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("network_type", sa.String(length=32), nullable=True),
        sa.Column("auth_type", sa.String(length=32), nullable=True),
        sa.Column("auth_key", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_ospfinterfaceintent_identity"),
    )
    op.create_index(op.f("ix_ospf_interface_intent_device_id"), "ospf_interface_intent", ["device_id"], unique=False)
    op.create_table(
        "redistribution_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("dest_protocol", sa.String(length=16), nullable=False),
        sa.Column("dest_ref", sa.String(length=128), nullable=False),
        sa.Column("source_protocol", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("route_map", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("metric_type", sa.String(length=16), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id",
            "dest_protocol",
            "dest_ref",
            "source_protocol",
            "source_ref",
            name="uq_redistributionintent_identity",
        ),
    )
    op.create_index(op.f("ix_redistribution_intent_device_id"), "redistribution_intent", ["device_id"], unique=False)
    op.create_table(
        "route_policy_object_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("entries", sa.JSON(), nullable=False),
        sa.Column("invert_match", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "family", "name", name="uq_rpoi_identity"),
    )
    op.create_index(
        op.f("ix_route_policy_object_intent_device_id"), "route_policy_object_intent", ["device_id"], unique=False
    )
    op.create_table(
        "snmp_community",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("community_hash", sa.String(length=64), nullable=False),
        sa.Column("access", sa.String(length=4), nullable=False),
        sa.Column("acl", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "community_hash", name="uq_snmpcommunity_device_hash"),
    )
    op.create_index(op.f("ix_snmp_community_device_id"), "snmp_community", ["device_id"], unique=False)
    op.create_table(
        "snmp_community_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("vault_ref", sa.String(length=512), nullable=False),
        sa.Column("access", sa.String(length=4), nullable=False),
        sa.Column("acl", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "label", name="uq_snmpcommintent_device_label"),
    )
    op.create_index(op.f("ix_snmp_community_intent_device_id"), "snmp_community_intent", ["device_id"], unique=False)
    op.create_table(
        "snmp_host",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=8), nullable=True),
        sa.Column("notify_type", sa.String(length=16), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_snmphost_device_address"),
    )
    op.create_index(op.f("ix_snmp_host_device_id"), "snmp_host", ["device_id"], unique=False)
    op.create_table(
        "snmp_host_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=4), nullable=False),
        sa.Column("notify_type", sa.String(length=8), nullable=False),
        sa.Column("community_or_user", sa.String(length=128), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "address", name="uq_snmphostintent_device_addr"),
    )
    op.create_index(op.f("ix_snmp_host_intent_device_id"), "snmp_host_intent", ["device_id"], unique=False)
    op.create_table(
        "snmp_system_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("contact", sa.String(length=256), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snmp_system_info_device_id"), "snmp_system_info", ["device_id"], unique=True)
    op.create_table(
        "snmp_system_info_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("contact", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snmp_system_info_intent_device_id"), "snmp_system_info_intent", ["device_id"], unique=True)
    op.create_table(
        "snmp_v3_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("has_auth_secret", sa.Boolean(), nullable=False),
        sa.Column("has_priv_secret", sa.Boolean(), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "username", name="uq_snmpv3user_device_username"),
    )
    op.create_index(op.f("ix_snmp_v3_user_device_id"), "snmp_v3_user", ["device_id"], unique=False)
    op.create_table(
        "snmp_v3_user_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("auth_vault_ref", sa.String(length=512), nullable=True),
        sa.Column("priv_vault_ref", sa.String(length=512), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "username", name="uq_snmpv3userintent_device_user"),
    )
    op.create_index(op.f("ix_snmp_v3_user_intent_device_id"), "snmp_v3_user_intent", ["device_id"], unique=False)
    op.create_table(
        "static_route_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("next_hop", sa.String(length=64), nullable=False),
        sa.Column("interface_next_hop", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.Integer(), nullable=True),
        sa.Column("permanent", sa.Boolean(), nullable=True),
        sa.Column("tag", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vrf", "prefix", "next_hop", name="uq_staticrouteintent_identity"),
    )
    op.create_index(op.f("ix_static_route_intent_device_id"), "static_route_intent", ["device_id"], unique=False)
    op.create_table(
        "subinterface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("parent_interface", sa.String(length=128), nullable=True),
        sa.Column("dot1q_vlan", sa.Integer(), nullable=True),
        sa.Column("sub_type", sa.String(length=16), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_subifintent_identity"),
    )
    op.create_index(op.f("ix_subinterface_intent_device_id"), "subinterface_intent", ["device_id"], unique=False)
    op.create_table(
        "svi_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.Column("svi_type", sa.String(length=8), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_sviintent_identity"),
    )
    op.create_index(op.f("ix_svi_intent_device_id"), "svi_intent", ["device_id"], unique=False)
    op.create_table(
        "vlan_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "vlan_id", name="uq_vlanintent_identity"),
    )
    op.create_index(op.f("ix_vlan_intent_device_id"), "vlan_intent", ["device_id"], unique=False)
    op.create_table(
        "bgp_scope_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("router_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["router_id"], ["bgp_router_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("router_id", "vrf", name="uq_bgpscopeintent_identity"),
    )
    op.create_index(op.f("ix_bgp_scope_intent_router_id"), "bgp_scope_intent", ["router_id"], unique=False)
    op.create_table(
        "device_bgp_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("router_id", sa.Integer(), nullable=False),
        sa.Column("vrf", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["router_id"], ["device_bgp_router.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("router_id", "vrf", name="uq_devicebgpscope_identity"),
    )
    op.create_index(op.f("ix_device_bgp_scope_router_id"), "device_bgp_scope", ["router_id"], unique=False)
    op.create_table(
        "device_route_policy_as_path_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("as_path_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["as_path_id"], ["device_route_policy_as_path.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("as_path_id", "sequence", name="uq_drpape_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_as_path_entry_as_path_id"),
        "device_route_policy_as_path_entry",
        ["as_path_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_community_list_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("community_list_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("community", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["community_list_id"], ["device_route_policy_community_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_list_id", "sequence", name="uq_drpcle_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_community_list_entry_community_list_id"),
        "device_route_policy_community_list_entry",
        ["community_list_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_prefix_list_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prefix_list_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("ge", sa.Integer(), nullable=True),
        sa.Column("le", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["prefix_list_id"], ["device_route_policy_prefix_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prefix_list_id", "sequence", name="uq_drpple_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_prefix_list_entry_prefix_list_id"),
        "device_route_policy_prefix_list_entry",
        ["prefix_list_id"],
        unique=False,
    )
    op.create_table(
        "device_route_policy_route_map_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_map_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("match_prefix_lists", sa.JSON(), nullable=True),
        sa.Column("match_community_lists", sa.JSON(), nullable=True),
        sa.Column("match_as_paths", sa.JSON(), nullable=True),
        sa.Column("match_json", sa.Text(), nullable=True),
        sa.Column("set_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["route_map_id"], ["device_route_policy_route_map.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_map_id", "sequence", name="uq_drprme_seq"),
    )
    op.create_index(
        op.f("ix_device_route_policy_route_map_entry_route_map_id"),
        "device_route_policy_route_map_entry",
        ["route_map_id"],
        unique=False,
    )
    op.create_table(
        "device_switchport",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=True),
        sa.Column("untagged_vlan_id", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["untagged_vlan_id"], ["device_vlan.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "interface_name", name="uq_deviceswitchport_identity"),
    )
    op.create_index(op.f("ix_device_switchport_device_id"), "device_switchport", ["device_id"], unique=False)
    op.create_table(
        "interface_attr_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("nso_value", sa.Text(), nullable=True),
        sa.Column("netbox_value", sa.Text(), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "imported",
                "changed",
                "error",
                "unknown",
                "accepted",
                "deploying",
                "in_sync",
                "apply_failed",
                "drifted",
                name="syncstate",
            ),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interface_id"],
            ["interfaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "attribute"),
    )
    op.create_index(
        op.f("ix_interface_attr_state_interface_id"), "interface_attr_state", ["interface_id"], unique=False
    )
    op.create_table(
        "interface_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("intent_value", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interface_id"],
            ["interfaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "attribute"),
    )
    op.create_index(op.f("ix_interface_intent_interface_id"), "interface_intent", ["interface_id"], unique=False)
    op.create_table(
        "interface_ip_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("vrf", sa.String(length=256), nullable=False),
        sa.Column("family", sa.String(length=8), nullable=False),
        sa.Column("secondary", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_apply_error", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["interface_id"], ["interfaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interface_id", "address", "vrf", name="uq_ifipintent_iface_addr_vrf"),
    )
    op.create_index(op.f("ix_interface_ip_intent_interface_id"), "interface_ip_intent", ["interface_id"], unique=False)
    op.create_table(
        "lag_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lag_interface_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=256), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["lag_interface_id"], ["lag_interface.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lag_interface_id", "interface_name", name="uq_lagmember_lag_iface"),
    )
    op.create_index(op.f("ix_lag_member_lag_interface_id"), "lag_member", ["lag_interface_id"], unique=False)
    op.create_table(
        "lag_member_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lag_bundle_id", sa.Integer(), nullable=False),
        sa.Column("interface_name", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=True),
        sa.Column("port_priority", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lag_bundle_id"], ["lag_bundle_config.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lag_bundle_id", "interface_name", name="uq_lag_member_config_bundle_iface"),
    )
    op.create_index(op.f("ix_lag_member_config_lag_bundle_id"), "lag_member_config", ["lag_bundle_id"], unique=False)
    op.create_table(
        "bgp_af_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["bgp_scope_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "af", name="uq_bgpafintent_identity"),
    )
    op.create_index(op.f("ix_bgp_af_intent_scope_id"), "bgp_af_intent", ["scope_id"], unique=False)
    op.create_table(
        "bgp_peer_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("peer_address", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("peer_group", sa.String(length=128), nullable=True),
        sa.Column("remote_as", sa.String(length=32), nullable=True),
        sa.Column("local_as", sa.String(length=32), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["scope_id"], ["bgp_scope_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "peer_address", name="uq_bgppeerintent_identity"),
    )
    op.create_index(op.f("ix_bgp_peer_intent_scope_id"), "bgp_peer_intent", ["scope_id"], unique=False)
    op.create_table(
        "device_bgp_address_family",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["device_bgp_scope.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "af", name="uq_devicebgpaf_identity"),
    )
    op.create_index(
        op.f("ix_device_bgp_address_family_scope_id"), "device_bgp_address_family", ["scope_id"], unique=False
    )
    op.create_table(
        "device_bgp_peer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("peer_address", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("peer_group", sa.String(length=128), nullable=True),
        sa.Column("remote_as", sa.String(length=32), nullable=True),
        sa.Column("local_as", sa.String(length=32), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.Column("bfd_enabled", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["scope_id"], ["device_bgp_scope.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "peer_address", name="uq_devicebgppeer_identity"),
    )
    op.create_index(op.f("ix_device_bgp_peer_scope_id"), "device_bgp_peer", ["scope_id"], unique=False)
    op.create_table(
        "device_bgp_peer_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("remote_as", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["scope_id"], ["device_bgp_scope.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id", "name", name="uq_devicebgppeergroup_identity"),
    )
    op.create_index(op.f("ix_device_bgp_peer_group_scope_id"), "device_bgp_peer_group", ["scope_id"], unique=False)
    op.create_table(
        "device_switchport_tagged_vlan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("switchport_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["switchport_id"], ["device_switchport.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vlan_id"], ["device_vlan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("switchport_id", "vlan_id", name="uq_swtaggedvlan_identity"),
    )
    op.create_table(
        "bgp_peer_af_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("routemap_in", sa.String(length=255), nullable=True),
        sa.Column("routemap_out", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_in", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_out", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["peer_id"], ["bgp_peer_intent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("peer_id", "af", name="uq_bgppeerafintent_identity"),
    )
    op.create_index(op.f("ix_bgp_peer_af_intent_peer_id"), "bgp_peer_af_intent", ["peer_id"], unique=False)
    op.create_table(
        "device_bgp_peer_af",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("routemap_in", sa.String(length=255), nullable=True),
        sa.Column("routemap_out", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_in", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_out", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["peer_id"], ["device_bgp_peer.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("peer_id", "af", name="uq_devicebgppeeraf_identity"),
    )
    op.create_index(op.f("ix_device_bgp_peer_af_peer_id"), "device_bgp_peer_af", ["peer_id"], unique=False)
    op.create_table(
        "device_bgp_peer_group_af",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("peer_group_id", sa.Integer(), nullable=False),
        sa.Column("af", sa.String(length=32), nullable=False),
        sa.Column("routemap_in", sa.String(length=255), nullable=True),
        sa.Column("routemap_out", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_in", sa.String(length=255), nullable=True),
        sa.Column("prefixlist_out", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["peer_group_id"], ["device_bgp_peer_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("peer_group_id", "af", name="uq_devicebgppeergroupaf_identity"),
    )
    op.create_index(
        op.f("ix_device_bgp_peer_group_af_peer_group_id"), "device_bgp_peer_group_af", ["peer_group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_bgp_peer_group_af_peer_group_id"), table_name="device_bgp_peer_group_af")
    op.drop_table("device_bgp_peer_group_af")
    op.drop_index(op.f("ix_device_bgp_peer_af_peer_id"), table_name="device_bgp_peer_af")
    op.drop_table("device_bgp_peer_af")
    op.drop_index(op.f("ix_bgp_peer_af_intent_peer_id"), table_name="bgp_peer_af_intent")
    op.drop_table("bgp_peer_af_intent")
    op.drop_table("device_switchport_tagged_vlan")
    op.drop_index(op.f("ix_device_bgp_peer_group_scope_id"), table_name="device_bgp_peer_group")
    op.drop_table("device_bgp_peer_group")
    op.drop_index(op.f("ix_device_bgp_peer_scope_id"), table_name="device_bgp_peer")
    op.drop_table("device_bgp_peer")
    op.drop_index(op.f("ix_device_bgp_address_family_scope_id"), table_name="device_bgp_address_family")
    op.drop_table("device_bgp_address_family")
    op.drop_index(op.f("ix_bgp_peer_intent_scope_id"), table_name="bgp_peer_intent")
    op.drop_table("bgp_peer_intent")
    op.drop_index(op.f("ix_bgp_af_intent_scope_id"), table_name="bgp_af_intent")
    op.drop_table("bgp_af_intent")
    op.drop_index(op.f("ix_lag_member_config_lag_bundle_id"), table_name="lag_member_config")
    op.drop_table("lag_member_config")
    op.drop_index(op.f("ix_lag_member_lag_interface_id"), table_name="lag_member")
    op.drop_table("lag_member")
    op.drop_index(op.f("ix_interface_ip_intent_interface_id"), table_name="interface_ip_intent")
    op.drop_table("interface_ip_intent")
    op.drop_index(op.f("ix_interface_intent_interface_id"), table_name="interface_intent")
    op.drop_table("interface_intent")
    op.drop_index(op.f("ix_interface_attr_state_interface_id"), table_name="interface_attr_state")
    op.drop_table("interface_attr_state")
    op.drop_index(op.f("ix_device_switchport_device_id"), table_name="device_switchport")
    op.drop_table("device_switchport")
    op.drop_index(
        op.f("ix_device_route_policy_route_map_entry_route_map_id"), table_name="device_route_policy_route_map_entry"
    )
    op.drop_table("device_route_policy_route_map_entry")
    op.drop_index(
        op.f("ix_device_route_policy_prefix_list_entry_prefix_list_id"),
        table_name="device_route_policy_prefix_list_entry",
    )
    op.drop_table("device_route_policy_prefix_list_entry")
    op.drop_index(
        op.f("ix_device_route_policy_community_list_entry_community_list_id"),
        table_name="device_route_policy_community_list_entry",
    )
    op.drop_table("device_route_policy_community_list_entry")
    op.drop_index(
        op.f("ix_device_route_policy_as_path_entry_as_path_id"), table_name="device_route_policy_as_path_entry"
    )
    op.drop_table("device_route_policy_as_path_entry")
    op.drop_index(op.f("ix_device_bgp_scope_router_id"), table_name="device_bgp_scope")
    op.drop_table("device_bgp_scope")
    op.drop_index(op.f("ix_bgp_scope_intent_router_id"), table_name="bgp_scope_intent")
    op.drop_table("bgp_scope_intent")
    op.drop_index(op.f("ix_vlan_intent_device_id"), table_name="vlan_intent")
    op.drop_table("vlan_intent")
    op.drop_index(op.f("ix_svi_intent_device_id"), table_name="svi_intent")
    op.drop_table("svi_intent")
    op.drop_index(op.f("ix_subinterface_intent_device_id"), table_name="subinterface_intent")
    op.drop_table("subinterface_intent")
    op.drop_index(op.f("ix_static_route_intent_device_id"), table_name="static_route_intent")
    op.drop_table("static_route_intent")
    op.drop_index(op.f("ix_snmp_v3_user_intent_device_id"), table_name="snmp_v3_user_intent")
    op.drop_table("snmp_v3_user_intent")
    op.drop_index(op.f("ix_snmp_v3_user_device_id"), table_name="snmp_v3_user")
    op.drop_table("snmp_v3_user")
    op.drop_index(op.f("ix_snmp_system_info_intent_device_id"), table_name="snmp_system_info_intent")
    op.drop_table("snmp_system_info_intent")
    op.drop_index(op.f("ix_snmp_system_info_device_id"), table_name="snmp_system_info")
    op.drop_table("snmp_system_info")
    op.drop_index(op.f("ix_snmp_host_intent_device_id"), table_name="snmp_host_intent")
    op.drop_table("snmp_host_intent")
    op.drop_index(op.f("ix_snmp_host_device_id"), table_name="snmp_host")
    op.drop_table("snmp_host")
    op.drop_index(op.f("ix_snmp_community_intent_device_id"), table_name="snmp_community_intent")
    op.drop_table("snmp_community_intent")
    op.drop_index(op.f("ix_snmp_community_device_id"), table_name="snmp_community")
    op.drop_table("snmp_community")
    op.drop_index(op.f("ix_route_policy_object_intent_device_id"), table_name="route_policy_object_intent")
    op.drop_table("route_policy_object_intent")
    op.drop_index(op.f("ix_redistribution_intent_device_id"), table_name="redistribution_intent")
    op.drop_table("redistribution_intent")
    op.drop_index(op.f("ix_ospf_interface_intent_device_id"), table_name="ospf_interface_intent")
    op.drop_table("ospf_interface_intent")
    op.drop_index(op.f("ix_ospf_instance_intent_device_id"), table_name="ospf_instance_intent")
    op.drop_table("ospf_instance_intent")
    op.drop_index(op.f("ix_managed_scope_device_id"), table_name="managed_scope")
    op.drop_table("managed_scope")
    op.drop_index(op.f("ix_logging_host_intent_device_id"), table_name="logging_host_intent")
    op.drop_table("logging_host_intent")
    op.drop_index(op.f("ix_lag_interface_device_id"), table_name="lag_interface")
    op.drop_table("lag_interface")
    op.drop_index(op.f("ix_lag_bundle_config_device_id"), table_name="lag_bundle_config")
    op.drop_table("lag_bundle_config")
    op.drop_index(op.f("ix_l2_sap_intent_device_id"), table_name="l2_sap_intent")
    op.drop_table("l2_sap_intent")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_isis_process_intent_device_id"), table_name="isis_process_intent")
    op.drop_table("isis_process_intent")
    op.drop_index(op.f("ix_isis_interface_intent_device_id"), table_name="isis_interface_intent")
    op.drop_table("isis_interface_intent")
    op.drop_index(op.f("ix_isis_flex_algo_intent_device_id"), table_name="isis_flex_algo_intent")
    op.drop_table("isis_flex_algo_intent")
    op.drop_index(op.f("ix_interfaces_device_id"), table_name="interfaces")
    op.drop_table("interfaces")
    op.drop_index(op.f("ix_interface_mtu_intent_device_id"), table_name="interface_mtu_intent")
    op.drop_table("interface_mtu_intent")
    op.drop_index(op.f("ix_interface_ip_address_device_id"), table_name="interface_ip_address")
    op.drop_table("interface_ip_address")
    op.drop_index(op.f("ix_device_vlan_device_id"), table_name="device_vlan")
    op.drop_table("device_vlan")
    op.drop_index(op.f("ix_device_svi_device_id"), table_name="device_svi")
    op.drop_table("device_svi")
    op.drop_index(op.f("ix_device_subinterface_device_id"), table_name="device_subinterface")
    op.drop_table("device_subinterface")
    op.drop_index(op.f("ix_device_static_route_device_id"), table_name="device_static_route")
    op.drop_table("device_static_route")
    op.drop_index(op.f("ix_device_settings_device_id"), table_name="device_settings")
    op.drop_table("device_settings")
    op.drop_index(op.f("ix_device_route_policy_route_map_device_id"), table_name="device_route_policy_route_map")
    op.drop_table("device_route_policy_route_map")
    op.drop_index(op.f("ix_device_route_policy_prefix_list_device_id"), table_name="device_route_policy_prefix_list")
    op.drop_table("device_route_policy_prefix_list")
    op.drop_index(
        op.f("ix_device_route_policy_community_list_device_id"), table_name="device_route_policy_community_list"
    )
    op.drop_table("device_route_policy_community_list")
    op.drop_index(op.f("ix_device_route_policy_as_path_device_id"), table_name="device_route_policy_as_path")
    op.drop_table("device_route_policy_as_path")
    op.drop_index(op.f("ix_device_redistribution_device_id"), table_name="device_redistribution")
    op.drop_table("device_redistribution")
    op.drop_index(op.f("ix_device_ospf_interface_device_id"), table_name="device_ospf_interface")
    op.drop_table("device_ospf_interface")
    op.drop_index(op.f("ix_device_ospf_instance_device_id"), table_name="device_ospf_instance")
    op.drop_table("device_ospf_instance")
    op.drop_index(op.f("ix_device_logging_host_device_id"), table_name="device_logging_host")
    op.drop_table("device_logging_host")
    op.drop_index(op.f("ix_device_l2_sap_device_id"), table_name="device_l2_sap")
    op.drop_table("device_l2_sap")
    op.drop_index(op.f("ix_device_isis_process_device_id"), table_name="device_isis_process")
    op.drop_table("device_isis_process")
    op.drop_index(op.f("ix_device_isis_interface_device_id"), table_name="device_isis_interface")
    op.drop_table("device_isis_interface")
    op.drop_index(op.f("ix_device_interface_mtu_device_id"), table_name="device_interface_mtu")
    op.drop_table("device_interface_mtu")
    op.drop_index(op.f("ix_device_failover_device_id"), table_name="device_failover")
    op.drop_table("device_failover")
    op.drop_index(op.f("ix_device_bgp_router_device_id"), table_name="device_bgp_router")
    op.drop_table("device_bgp_router")
    op.drop_index(op.f("ix_device_bfd_interface_device_id"), table_name="device_bfd_interface")
    op.drop_table("device_bfd_interface")
    op.drop_index(op.f("ix_bgp_router_intent_device_id"), table_name="bgp_router_intent")
    op.drop_table("bgp_router_intent")
    op.drop_index(op.f("ix_bfd_intent_device_id"), table_name="bfd_intent")
    op.drop_table("bfd_intent")
    op.drop_table("failover_config")
    op.drop_index(op.f("ix_devices_nso_device_name"), table_name="devices")
    op.drop_index(op.f("ix_devices_netbox_device_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_device_capability_sw_version"), table_name="device_capability")
    op.drop_index(op.f("ix_device_capability_ned_id"), table_name="device_capability")
    op.drop_table("device_capability")
    # ### end Alembic commands ###
